//! WASM entrypoint for the DAQ Control Panel.
//!
//! This binary bootstraps the **full** `DaqApp` (same panels as native desktop)
//! in a browser via WebGL, connecting to a remote daemon over gRPC-web.
//!
//! # Build & Serve
//!
//! ```bash
//! # Install trunk (WASM build tool)
//! cargo install trunk --locked
//!
//! # Build and serve locally (auto-rebuilds on change)
//! cd crates/ui && trunk serve
//!
//! # Production build
//! cd crates/ui && trunk build --release
//! ```

// Only compile this binary for the `web` feature
#[cfg(not(feature = "web"))]
fn main() {
    eprintln!("The rust-daq-web binary requires the 'web' feature.");
    std::process::exit(1);
}

#[cfg(all(feature = "web", target_arch = "wasm32"))]
fn main() {
    // This function is never called on WASM — the real entrypoint is `start()` below.
    // Trunk calls the wasm_bindgen start function directly.
}

#[cfg(all(feature = "web", target_arch = "wasm32"))]
mod web {
    use wasm_bindgen::JsCast;
    use wasm_bindgen::prelude::*;

    /// Browser entrypoint — called by the JS glue code generated by wasm-bindgen.
    ///
    /// Initializes logging, creates an eframe `WebRunner`, and launches the full
    /// `DaqApp` (same dock layout, panels, and widgets as the native desktop GUI).
    #[wasm_bindgen(start)]
    pub fn start() -> Result<(), JsValue> {
        // Set up panic hook for readable error messages in the browser console
        console_error_panic_hook::set_once();

        // Initialize tracing for WASM (outputs to browser console)
        tracing_wasm::set_as_global_default();

        tracing::info!("DAQ Control Panel (WASM) starting...");

        // Install automation API at window.daqGui before eframe launch
        // so automation scripts can issue commands during initialization.
        ui::automation::install_automation_api();

        // Launch the eframe web app with the full DaqApp
        wasm_bindgen_futures::spawn_local(async {
            let web_options = eframe::WebOptions::default();

            // eframe 0.33 requires an HtmlCanvasElement, not a string ID
            let document = web_sys::window()
                .expect("no window")
                .document()
                .expect("no document");
            let canvas = document
                .get_element_by_id("daq_canvas")
                .expect("no canvas element with id 'daq_canvas'")
                .dyn_into::<web_sys::HtmlCanvasElement>()
                .expect("element is not a canvas");

            eframe::WebRunner::new()
                .start(
                    canvas,
                    web_options,
                    Box::new(|cc| Ok(Box::new(ui::app::DaqApp::new_wasm(cc)))),
                )
                .await
                .expect("Failed to start eframe");
        });

        Ok(())
    }
}

// Native stub when web feature is enabled but not on wasm target
#[cfg(all(feature = "web", not(target_arch = "wasm32")))]
fn main() {
    eprintln!("The rust-daq-web binary must be compiled for wasm32-unknown-unknown.");
    eprintln!("Use: trunk serve (from crates/ui/)");
    std::process::exit(1);
}
