//! WASM entrypoint for the DAQ Control Panel.
//!
//! This binary runs the egui GUI in a browser via WebGL, connecting to
//! a remote daemon over gRPC-web. The daemon runs natively on a lab machine;
//! only this GUI runs in the browser.
//!
//! # Build & Serve
//!
//! ```bash
//! # Install trunk (WASM build tool)
//! cargo install trunk --locked
//!
//! # Build and serve locally (auto-rebuilds on change)
//! cd crates/ui && trunk serve
//!
//! # Production build
//! cd crates/ui && trunk build --release
//! ```

// Only compile this binary for the `web` feature
#[cfg(not(feature = "web"))]
fn main() {
    eprintln!("The rust-daq-web binary requires the 'web' feature.");
    std::process::exit(1);
}

#[cfg(all(feature = "web", target_arch = "wasm32"))]
mod web_schema;

#[cfg(all(feature = "web", target_arch = "wasm32"))]
fn main() {
    // This function is never called on WASM — the real entrypoint is `start()` below.
    // Trunk calls the wasm_bindgen start function directly.
}

#[cfg(all(feature = "web", target_arch = "wasm32"))]
mod web {
    use eframe::egui;
    use std::collections::HashMap;
    use wasm_bindgen::prelude::*;
    use wasm_bindgen::JsCast;

    /// Browser entrypoint — called by the JS glue code generated by wasm-bindgen.
    #[wasm_bindgen(start)]
    pub fn start() -> Result<(), JsValue> {
        // Set up panic hook for readable error messages in the browser console
        console_error_panic_hook::set_once();

        // Initialize tracing for WASM (outputs to browser console)
        tracing_wasm::set_as_global_default();

        tracing::info!("DAQ Control Panel (WASM) starting...");

        // Launch the eframe web app
        wasm_bindgen_futures::spawn_local(async {
            let web_options = eframe::WebOptions::default();

            // eframe 0.33 requires an HtmlCanvasElement, not a string ID
            let document = web_sys::window()
                .expect("no window")
                .document()
                .expect("no document");
            let canvas = document
                .get_element_by_id("daq_canvas")
                .expect("no canvas element with id 'daq_canvas'")
                .dyn_into::<web_sys::HtmlCanvasElement>()
                .expect("element is not a canvas");

            eframe::WebRunner::new()
                .start(
                    canvas,
                    web_options,
                    Box::new(|cc| Ok(Box::new(DaqWebApp::new(cc)))),
                )
                .await
                .expect("Failed to start eframe");
        });

        Ok(())
    }

    /// Connection state for the web app.
    enum ConnectionState {
        /// Not yet connected — showing the URL input form.
        Disconnected,
        /// Attempting to connect.
        Connecting,
        /// Connected to daemon; devices loaded.
        Connected {
            client: client::DaqClient,
            devices: Vec<protocol::daq::DeviceInfo>,
        },
        /// Connection or RPC failed.
        Error(String),
    }

    /// Minimal web-based DAQ control panel.
    ///
    /// Unlike the full native `DaqApp`, this stripped-down version:
    /// - No daemon auto-start (daemon runs on lab machine)
    /// - No SSH tunneling
    /// - No reconnection logic (simple connect + poll)
    /// - Uses config-driven panels from `ui_schema_json` metadata
    struct DaqWebApp {
        /// Daemon URL (e.g., "http://10.0.0.40:50051")
        daemon_url: String,
        /// Current connection state
        state: ConnectionState,
        /// Pending device list refresh
        refresh_rx:
            Option<tokio::sync::oneshot::Receiver<Result<Vec<protocol::daq::DeviceInfo>, String>>>,
        /// Pending command results (device_id -> result)
        pending_commands: HashMap<String, tokio::sync::oneshot::Receiver<Result<String, String>>>,
        /// Cached command results for display
        command_results: HashMap<String, Result<String, String>>,
    }

    impl DaqWebApp {
        fn new(_cc: &eframe::CreationContext<'_>) -> Self {
            Self {
                daemon_url: "http://10.0.0.40:50051".to_string(),
                state: ConnectionState::Disconnected,
                refresh_rx: None,
                pending_commands: HashMap::new(),
                command_results: HashMap::new(),
            }
        }

        fn connect(&mut self) {
            let url = self.daemon_url.clone();
            self.state = ConnectionState::Connecting;

            let (tx, rx) = tokio::sync::oneshot::channel();
            self.refresh_rx = Some(rx);

            wasm_bindgen_futures::spawn_local(async move {
                let mut client = client::DaqClient::connect_web(&url);
                match client.list_devices().await {
                    Ok(devices) => {
                        let _ = tx.send(Ok(devices));
                    }
                    Err(e) => {
                        let _ = tx.send(Err(format!("{e}")));
                    }
                }
            });
        }

        fn refresh_devices(
            client: &client::DaqClient,
        ) -> tokio::sync::oneshot::Receiver<Result<Vec<protocol::daq::DeviceInfo>, String>>
        {
            let (tx, rx) = tokio::sync::oneshot::channel();
            let mut c = client.clone();
            wasm_bindgen_futures::spawn_local(async move {
                match c.list_devices().await {
                    Ok(devices) => {
                        let _ = tx.send(Ok(devices));
                    }
                    Err(e) => {
                        let _ = tx.send(Err(format!("{e}")));
                    }
                }
            });
            rx
        }

        fn execute_command(&mut self, device_id: &str, command: &str, args: &str) {
            if let ConnectionState::Connected { client, .. } = &self.state {
                let (tx, rx) = tokio::sync::oneshot::channel();
                let mut c = client.clone();
                let did = device_id.to_string();
                let cmd = command.to_string();
                let a = args.to_string();
                wasm_bindgen_futures::spawn_local(async move {
                    match c.execute_device_command(&did, &cmd, &a).await {
                        Ok(resp) => {
                            let _ = tx.send(Ok(resp.results));
                        }
                        Err(e) => {
                            let _ = tx.send(Err(format!("{e}")));
                        }
                    }
                });
                self.pending_commands
                    .insert(format!("{device_id}:{command}"), rx);
            }
        }

        /// Poll all pending async operations.
        fn poll_pending(&mut self) {
            // Poll device list refresh
            if let Some(rx) = &mut self.refresh_rx {
                if let Ok(result) = rx.try_recv() {
                    match result {
                        Ok(devices) => {
                            // Need to reconstruct the client from URL
                            let client = client::DaqClient::connect_web(&self.daemon_url);
                            self.state = ConnectionState::Connected { client, devices };
                        }
                        Err(e) => {
                            self.state = ConnectionState::Error(e);
                        }
                    }
                    self.refresh_rx = None;
                }
            }

            // Poll pending command results
            let mut completed = Vec::new();
            for (key, rx) in &mut self.pending_commands {
                if let Ok(result) = rx.try_recv() {
                    self.command_results.insert(key.clone(), result);
                    completed.push(key.clone());
                }
            }
            for key in completed {
                self.pending_commands.remove(&key);
            }
        }
    }

    impl eframe::App for DaqWebApp {
        fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
            // Poll async operations
            self.poll_pending();

            // Request repaint to keep polling (60fps is fine for a control panel)
            ctx.request_repaint_after(std::time::Duration::from_millis(100));

            egui::TopBottomPanel::top("top_bar").show(ctx, |ui| {
                ui.horizontal(|ui| {
                    ui.heading("DAQ Control Panel");
                    ui.separator();
                    match &self.state {
                        ConnectionState::Disconnected => {
                            ui.colored_label(egui::Color32::GRAY, "Disconnected");
                        }
                        ConnectionState::Connecting => {
                            ui.spinner();
                            ui.label("Connecting...");
                        }
                        ConnectionState::Connected { devices, .. } => {
                            ui.colored_label(
                                egui::Color32::GREEN,
                                format!("Connected ({} devices)", devices.len()),
                            );
                        }
                        ConnectionState::Error(e) => {
                            ui.colored_label(egui::Color32::RED, format!("Error: {e}"));
                        }
                    }
                });
            });

            egui::CentralPanel::default().show(ctx, |ui| match &self.state {
                ConnectionState::Disconnected | ConnectionState::Error(_) => {
                    ui.vertical_centered(|ui| {
                        ui.add_space(40.0);
                        ui.heading("Connect to DAQ Daemon");
                        ui.add_space(20.0);
                        ui.horizontal(|ui| {
                            ui.label("Daemon URL:");
                            ui.text_edit_singleline(&mut self.daemon_url);
                        });
                        ui.add_space(10.0);
                        if ui.button("Connect").clicked() {
                            self.connect();
                        }
                        if let ConnectionState::Error(e) = &self.state {
                            ui.add_space(10.0);
                            ui.colored_label(egui::Color32::RED, e);
                        }
                    });
                }
                ConnectionState::Connecting => {
                    ui.vertical_centered(|ui| {
                        ui.add_space(80.0);
                        ui.spinner();
                        ui.label("Connecting to daemon...");
                    });
                }
                ConnectionState::Connected { devices, .. } => {
                    self.render_devices(ui, devices.clone());
                }
            });
        }
    }

    impl DaqWebApp {
        fn render_devices(&mut self, ui: &mut egui::Ui, devices: Vec<protocol::daq::DeviceInfo>) {
            // Refresh button
            ui.horizontal(|ui| {
                if ui.button("Refresh Devices").clicked() {
                    if let ConnectionState::Connected { client, .. } = &self.state {
                        self.refresh_rx = Some(Self::refresh_devices(client));
                    }
                }
                if ui.button("Disconnect").clicked() {
                    self.state = ConnectionState::Disconnected;
                }
            });
            ui.separator();

            // Render each device
            egui::ScrollArea::vertical().show(ui, |ui| {
                for device in &devices {
                    self.render_device_panel(ui, device);
                    ui.add_space(8.0);
                }
            });
        }

        fn render_device_panel(&mut self, ui: &mut egui::Ui, device: &protocol::daq::DeviceInfo) {
            let device_name = device.name.as_str();
            let device_id = device.id.as_str();
            let driver_type = device.driver_type.as_str();

            egui::CollapsingHeader::new(egui::RichText::new(device_name).heading())
                .default_open(true)
                .id_salt(device_id)
                .show(ui, |ui| {
                    ui.horizontal(|ui| {
                        ui.label(format!("ID: {device_id}"));
                        ui.separator();
                        ui.label(format!("Driver: {driver_type}"));
                    });

                    // Try to render config-driven panel from ui_schema_json
                    if let Some(metadata) = &device.metadata {
                        if let Some(json_str) = &metadata.ui_schema_json {
                            match serde_json::from_str::<super::web_schema::UiConfig>(json_str) {
                                Ok(ui_config) => {
                                    if let Some(panel) = &ui_config.control_panel {
                                        self.render_config_panel(ui, device_id, panel);
                                        return;
                                    }
                                }
                                Err(e) => {
                                    ui.colored_label(
                                        egui::Color32::YELLOW,
                                        format!("UI schema parse error: {e}"),
                                    );
                                }
                            }
                        }
                    }

                    // Fallback: show capabilities
                    ui.label("No config-driven panel available. Capabilities:");
                    for cap in &device.capabilities {
                        ui.label(format!("  - {cap}"));
                    }
                });
        }

        fn render_config_panel(
            &mut self,
            ui: &mut egui::Ui,
            device_id: &str,
            panel: &super::web_schema::ControlPanelConfig,
        ) {
            use super::web_schema::ControlSection;

            for section in &panel.sections {
                match section {
                    ControlSection::Sensor(cfg) => {
                        ui.horizontal(|ui| {
                            ui.label(&cfg.label);
                            ui.separator();
                            // Show last read value or "—"
                            let key = format!("{device_id}:read");
                            if let Some(result) = self.command_results.get(&key) {
                                match result {
                                    Ok(val) => {
                                        ui.monospace(format!(
                                            "{val} {}",
                                            cfg.unit.as_deref().unwrap_or("")
                                        ));
                                    }
                                    Err(e) => {
                                        ui.colored_label(egui::Color32::RED, e);
                                    }
                                }
                            } else {
                                ui.monospace("—");
                            }
                            if ui.small_button("Read").clicked() {
                                self.execute_command(device_id, "read", "");
                            }
                        });
                    }
                    ControlSection::CustomAction(cfg) => {
                        ui.horizontal(|ui| {
                            // Apply button style coloring
                            let clicked = match cfg.style {
                                super::web_schema::ButtonStyle::Danger => {
                                    ui.visuals_mut().widgets.inactive.weak_bg_fill =
                                        egui::Color32::from_rgb(180, 40, 40);
                                    ui.button(
                                        egui::RichText::new(&cfg.label).color(egui::Color32::WHITE),
                                    )
                                    .clicked()
                                }
                                super::web_schema::ButtonStyle::Success => {
                                    ui.visuals_mut().widgets.inactive.weak_bg_fill =
                                        egui::Color32::from_rgb(40, 140, 40);
                                    ui.button(
                                        egui::RichText::new(&cfg.label).color(egui::Color32::WHITE),
                                    )
                                    .clicked()
                                }
                                _ => ui.button(&cfg.label).clicked(),
                            };
                            if clicked {
                                // Serialize params to JSON string for the command args
                                let args = if cfg.params.is_empty() {
                                    String::new()
                                } else {
                                    serde_json::to_string(&cfg.params).unwrap_or_default()
                                };
                                self.execute_command(device_id, &cfg.command, &args);
                            }
                            let key = format!("{device_id}:{}", cfg.command);
                            if let Some(Ok(val)) = self.command_results.get(&key) {
                                if !val.is_empty() {
                                    ui.label(val);
                                }
                            }
                        });
                    }
                    ControlSection::Parameter(cfg) => {
                        ui.horizontal(|ui| {
                            ui.label(&cfg.label);
                            ui.separator();
                            // Show current value
                            let read_key = format!(
                                "{device_id}:{}",
                                cfg.read_command.as_deref().unwrap_or(&cfg.parameter)
                            );
                            if let Some(result) = self.command_results.get(&read_key) {
                                match result {
                                    Ok(val) => {
                                        ui.monospace(val);
                                    }
                                    Err(e) => {
                                        ui.colored_label(egui::Color32::RED, e);
                                    }
                                }
                            } else {
                                ui.monospace("—");
                            }
                            if let Some(cmd) = &cfg.read_command {
                                if ui.small_button("Read").clicked() {
                                    self.execute_command(device_id, cmd, "");
                                }
                            }
                        });
                    }
                    ControlSection::StatusDisplay(cfg) => {
                        ui.horizontal(|ui| {
                            ui.label(&cfg.label);
                            ui.separator();
                            // Read each status parameter
                            if cfg.parameters.is_empty() {
                                ui.monospace("—");
                            } else {
                                for param in &cfg.parameters {
                                    let key = format!("{device_id}:read_{param}");
                                    if let Some(result) = self.command_results.get(&key) {
                                        match result {
                                            Ok(val) => {
                                                ui.monospace(format!("{param}: {val}"));
                                            }
                                            Err(e) => {
                                                ui.colored_label(egui::Color32::RED, e);
                                            }
                                        }
                                    } else {
                                        ui.monospace(format!("{param}: —"));
                                    }
                                }
                                if ui.small_button("Refresh").clicked() {
                                    for param in &cfg.parameters {
                                        self.execute_command(
                                            device_id,
                                            &format!("read_{param}"),
                                            "",
                                        );
                                    }
                                }
                            }
                        });
                    }
                    ControlSection::Separator(_) => {
                        ui.separator();
                    }
                    _ => {
                        // Other section types rendered as generic labels
                        ui.label(format!("{section:?}"));
                    }
                }
            }
        }
    }
}

// Native stub when web feature is enabled but not on wasm target
#[cfg(all(feature = "web", not(target_arch = "wasm32")))]
fn main() {
    eprintln!("The rust-daq-web binary must be compiled for wasm32-unknown-unknown.");
    eprintln!("Use: trunk serve (from crates/ui/)");
    std::process::exit(1);
}
