[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
common = { path = "../common" }
hardware = { path = "../hardware" }
driver-registry = { path = "../driver-registry", features = ["all_hardware"] }
experiment = { path = "../experiment" }
daq-modules = { path = "../daq-modules", features = ["scripting", "native_plugins"], optional = true }
driver-mock = { path = "../driver-mock" }
storage = { path = "../storage" }
protocol = { path = "../protocol" }
server = { path = "../server", optional = true }
scripting = { path = "../scripting", optional = true }
ui = { path = "../ui" }
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing.workspace = true
serde_json.workspace = true
uuid = { version = "1.10", features = ["v4", "serde"] }
futures.workspace = true
async-trait.workspace = true
tempfile.workspace = true
chrono.workspace = true
tonic = { workspace = true, features = ["transport"] }
tokio-stream = { version = "0.1", features = ["sync"] }
hdf5 = { package = "hdf5-metno", version = "0.11.0" }
arrow = { version = "57", features = ["ipc"] }
nix = { version = "0.29", features = ["term"] }
driver-pvcam = { path = "../driver-pvcam", optional = true }
driver-universal = { path = "../driver-universal", features = ["emulator"], optional = true }
db = { path = "../db", optional = true }

[dev-dependencies]
serial_test = "3.1.1"
toml.workspace = true
tokio-test = "0.4"
tracing-test = "0.2"
tracing-subscriber = { version = "0.3", features = ["registry"] }


[features]
default = ["networking", "server", "scripting", "storage_hdf5", "storage_arrow", "native_plugins", "serial", "thorlabs", "newport", "newport_power_meter", "modules", "pvcam", "universal", "db-surreal-mem"]
networking = ["server/networking"]
server = ["dep:server", "networking"]
scripting = ["dep:scripting"]
storage_hdf5 = ["storage/storage_hdf5", "server/storage_hdf5"]
storage_arrow = ["storage/storage_arrow", "server/storage_arrow", "common/storage_arrow"]
pvcam = ["dep:driver-pvcam", "driver-registry/pvcam"]
pvcam_sdk = ["pvcam", "driver-registry/pvcam_sdk"]
gui_egui = ["ui/standalone"]
hardware_tests = []
libs_drivers = []
libs_spirit_driver = []
spectra_physics = ["driver-registry/spectra_physics"]
native_plugins = ["daq-modules/native_plugins"]
serial = ["hardware/serial", "driver-registry/serial"]
thorlabs = ["driver-registry/thorlabs"]
newport = ["driver-registry/newport"]
newport_power_meter = ["driver-registry/newport_power_meter"]
modules = ["daq-modules"]
universal = ["dep:driver-universal"]
db-surreal-mem = ["dep:db", "db/kv-mem", "dep:server", "server/db-surreal-mem"]
db-surreal-rocksdb = ["dep:db", "db/kv-rocksdb", "dep:server", "server/db-surreal-rocksdb"]

[lints]
workspace = true
