[server]
bind_address = "127.0.0.1:50051"

[[plugins]]
path = "../CF-LIBS/rust-plugin/target/debug/libcflibs_plugin.dylib"

[[modules]]
name = "inversion"
type = "cflibs-plugin.cflibs_inversion"

[modules.parameters]
model_path = "/Users/briansquires/code/CF-LIBS"
