#!/usr/bin/env bash
# generate-feature-matrix.sh — Extract feature information from cargo metadata
#
# Generates a markdown feature matrix from the actual Cargo.toml definitions,
# then optionally compares it against docs/reference/feature-matrix.md to
# flag drift.
#
# Usage:
#   bash scripts/generate-feature-matrix.sh              # Print markdown to stdout
#   bash scripts/generate-feature-matrix.sh --check      # Compare against docs, exit 1 on drift
#   bash scripts/generate-feature-matrix.sh --output FILE # Write markdown to FILE
#
# Requirements: jq (for JSON parsing)

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

# ─── Arguments ──────────────────────────────────────────────────────
MODE="print"      # print | check | output
OUTPUT_FILE=""

for arg in "$@"; do
    case "$arg" in
        --check)  MODE="check" ;;
        --output) MODE="output" ;;
        *)
            if [ "$MODE" = "output" ] && [ -z "$OUTPUT_FILE" ]; then
                OUTPUT_FILE="$arg"
                MODE="output"
            else
                echo "Usage: $0 [--check | --output FILE]" >&2
                exit 1
            fi
            ;;
    esac
done

if [ "$MODE" = "output" ] && [ -z "$OUTPUT_FILE" ]; then
    echo "Error: --output requires a file path argument" >&2
    exit 1
fi

# ─── Dependency check ──────────────────────────────────────────────
if ! command -v jq >/dev/null 2>&1; then
    echo "Error: jq is required. Install via: brew install jq / apt install jq" >&2
    exit 1
fi

# ─── Extract metadata ──────────────────────────────────────────────
METADATA_JSON="$(cargo metadata --no-deps --format-version 1 2>/dev/null)"

generate_matrix() {
    local metadata="$1"

    cat <<'HEADER'
# Feature Matrix (Auto-Generated)

> **This file is generated by `scripts/generate-feature-matrix.sh`.**
> Do not edit manually. Re-generate with: `bash scripts/generate-feature-matrix.sh --output docs/reference/feature-matrix-generated.md`

HEADER

    echo "## Workspace Crates and Features"
    echo ""

    # Extract package list, sorted by name
    local packages
    packages="$(echo "$metadata" | jq -r '.packages | sort_by(.name) | .[].name')"

    for pkg in $packages; do
        local features_json
        features_json="$(echo "$metadata" | jq -r --arg name "$pkg" '
            .packages[] | select(.name == $name) | .features // empty')"

        # Skip crates with no features
        local feature_count
        feature_count="$(echo "$features_json" | jq 'length')"
        if [ "$feature_count" -eq 0 ]; then
            continue
        fi

        # Get the default features
        local defaults
        defaults="$(echo "$features_json" | jq -r '.default // [] | join(", ")')"

        echo "### $pkg"
        echo ""
        if [ -n "$defaults" ]; then
            echo "**Default features:** $defaults"
        else
            echo "**Default features:** *(none)*"
        fi
        echo ""
        echo "| Feature | Activates |"
        echo "|---------|-----------|"

        # List each feature (excluding "default")
        echo "$features_json" | jq -r '
            to_entries
            | sort_by(.key)
            | .[]
            | select(.key != "default")
            | "| `\(.key)` | \(if (.value | length) == 0 then "*(standalone)*" else (.value | join(", ") | gsub("\\|"; "\\|")) end) |"
        '

        echo ""
    done

    # ── Summary statistics ────────────────────────────────────────
    echo "## Summary"
    echo ""

    local total_crates
    total_crates="$(echo "$metadata" | jq '.packages | length')"

    local crates_with_features
    crates_with_features="$(echo "$metadata" | jq '[.packages[] | select((.features | length) > 0)] | length')"

    local total_features
    total_features="$(echo "$metadata" | jq '[.packages[].features | to_entries[] | select(.key != "default")] | length')"

    echo "| Metric | Count |"
    echo "|--------|-------|"
    echo "| Total workspace crates | $total_crates |"
    echo "| Crates with features | $crates_with_features |"
    echo "| Total feature flags (excluding default) | $total_features |"
    echo ""

    # ── Key feature groups ────────────────────────────────────────
    echo "## Key Feature Groups"
    echo ""
    echo "### bin crate (daemon entry point)"
    echo ""
    echo "$metadata" | jq -r '
        .packages[] | select(.name == "bin") | .features
        | to_entries | sort_by(.key) | .[]
        | "- **\(.key)**: \(if (.value | length) == 0 then "*(standalone)*" else (.value | join(", ")) end)"
    '
    echo ""

    echo "### driver-registry (hardware driver gating)"
    echo ""
    echo "$metadata" | jq -r '
        .packages[] | select(.name == "driver-registry") | .features
        | to_entries | sort_by(.key) | .[]
        | "- **\(.key)**: \(if (.value | length) == 0 then "*(standalone)*" else (.value | join(", ")) end)"
    '
    echo ""

    echo "### storage (storage backends)"
    echo ""
    echo "$metadata" | jq -r '
        .packages[] | select(.name == "storage") | .features
        | to_entries | sort_by(.key) | .[]
        | "- **\(.key)**: \(if (.value | length) == 0 then "*(standalone)*" else (.value | join(", ")) end)"
    '
    echo ""

    echo "### ui (GUI application)"
    echo ""
    echo "$metadata" | jq -r '
        .packages[] | select(.name == "ui") | .features
        | to_entries | sort_by(.key) | .[]
        | "- **\(.key)**: \(if (.value | length) == 0 then "*(standalone)*" else (.value | join(", ")) end)"
    '
    echo ""

    echo "---"
    echo ""
    echo "*Generated on $(date -u '+%Y-%m-%d %H:%M UTC') from cargo metadata.*"
}

# ─── Main logic ─────────────────────────────────────────────────────
GENERATED="$(generate_matrix "$METADATA_JSON")"

case "$MODE" in
    print)
        echo "$GENERATED"
        ;;

    output)
        echo "$GENERATED" > "$OUTPUT_FILE"
        echo "Feature matrix written to $OUTPUT_FILE"
        ;;

    check)
        # Compare generated feature data against the curated docs/reference/feature-matrix.md.
        # Rather than a full diff (which would always differ due to formatting), we check
        # that every feature declared in cargo metadata is mentioned somewhere in the docs.

        DOCS_FILE="docs/reference/feature-matrix.md"
        if [ ! -f "$DOCS_FILE" ]; then
            echo "Error: $DOCS_FILE not found" >&2
            exit 1
        fi

        drift_found=0
        docs_content="$(cat "$DOCS_FILE")"

        echo "Checking feature documentation coverage..."
        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        # Check that every feature in cargo metadata is mentioned in the docs
        while IFS=$'\t' read -r pkg feature; do
            # Skip "default" pseudo-feature
            [ "$feature" = "default" ] && continue

            # Check if the feature name appears in the docs file
            if ! echo "$docs_content" | grep -qF "$feature"; then
                echo "  DRIFT: feature '$feature' (crate: $pkg) not found in $DOCS_FILE"
                drift_found=1
            fi
        done < <(echo "$METADATA_JSON" | jq -r '
            .packages[]
            | .name as $pkg
            | .features // {}
            | to_entries[]
            | "\($pkg)\t\(.key)"
        ')

        # Check that every crate with features is mentioned in the docs
        while IFS= read -r pkg; do
            if ! echo "$docs_content" | grep -qF "$pkg"; then
                echo "  DRIFT: crate '$pkg' has features but is not mentioned in $DOCS_FILE"
                drift_found=1
            fi
        done < <(echo "$METADATA_JSON" | jq -r '
            [.packages[] | select((.features | length) > 0) | .name] | sort | .[]
        ')

        echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

        if [ "$drift_found" -eq 1 ]; then
            echo ""
            echo "Feature documentation drift detected."
            echo "Update $DOCS_FILE or re-generate with:"
            echo "  bash scripts/generate-feature-matrix.sh --output docs/reference/feature-matrix-generated.md"
            exit 1
        else
            echo "All features are documented. No drift detected."
            exit 0
        fi
        ;;
esac
